### ISSUE TITLE
Show name

### ISSUE THREAD

**Issue by mabogdan1981** [AlixBa/addic7ed-subtitles#10]
Hello.
I have an issue with show name from shows.json.
For example in shows.json i have - "travelers": "6042"
but my file is "Travelers.2016.S01E12.HDTV.x264-FLEET".
Because of that year i get a message that show is missing.

Another exemple "shooter2016": "5842"
but my file is "Shooter.S01E08.HDTV.x264-FLEET".
Again i get a message that show is missing

How can i remove show year from shows.json forever.

I can modify manually and working but when i update shows.json i need again to modify al shows that not working.

Thank you very much for your work.

**Comment by AlixBa** [comment]
Hello :)

I already had this problem and there is a solution using mapping between show names.
https://github.com/AlixBa/addic7ed-subtitles/blob/master/src/AlixBa/Addic7edSubtitles/Jobs/ShowsUpdater.php#L94

I will push a fix!

**Comment by AlixBa** [comment]
<img width="1153" alt="capture d ecran 2017-01-05 a 10 28 03" src="https://cloud.githubusercontent.com/assets/2699647/21675289/a9e7e0aa-d331-11e6-81d8-40e0af8c2ac1.png">

**Comment by mabogdan1981** [comment]
Thank you very much.
I tried with this:

if ($this->nonEmptyShow($showsSeasons[$n])) {
                **_$name = preg_replace('/(d{4})$/', '', Episode::sanitizeShowName($show[0]));_**
                // if multiple shows name reference the same id
                if (isset($this->mappedShowsNames()[$name])) {
                    foreach ($this->mappedShowsNames()[$name] as $name) {
                        $shows[$name] = $id;
                    }
                } else {
                    $shows[$name] = $id;
                }
            }

to remove year from show update because it already have show id and it worked for me, but i think your method is much better.
I saw mapped shows and i tried but for me it didn't work. 
Maybe i did something wrong then.
Problem is that probably there are more shows with this problem and i use your class with a cronjob so i don't see the result and every time when a show not working i have to try manually to see what is the problem with him and i tried to avoid that.
Anyway, thank you very much for your response and i will try to use your solution.

**Comment by AlixBa** [comment]
You can see the fix [here](https://github.com/AlixBa/addic7ed-subtitles/commit/432903c0f3a726fca2c4af465a1ecbf38f6342e4#diff-c9bbd6c1f33d2a080d4f014bf399a64eR103)

`'travelers' => ['travelers', 'travelers2016']`

means that when `travelers` is found as a show name in Addic7ed, it will create 2 entries `travelers` and `travelers2016` in `shows.json` with the same id. See [this](https://github.com/AlixBa/addic7ed-subtitles/commit/432903c0f3a726fca2c4af465a1ecbf38f6342e4#diff-bf662c0eefe850fd95d95c9066b5daadR3741)

```
+    "travelers": "6042",
+    "travelers2016": "6042",
```

You can update with composer or pull the latest master to get this change :).
Do not hesitate to ask for mappings or PR some if you need!

EDIT:
For your cron, maybe you could save the script output the a file and then grep on errors like `Missing show`, etc. It will give you some reports you could use to see what happened

**Comment by mabogdan1981** [comment]
Ok.
 I already update with composer.
 I will see for future shows how is working.
Thank you very much.
