### ISSUE TITLE
shows.json no longer update

### ISSUE THREAD

**Issue by mabogdan1981** [AlixBa/addic7ed-subtitles#11]
I tried today to update shows.json because of new series "Powerless" and "Training Day".
On Addic7ed shows exist but when when i update shows.json this show don't appear.
If i put mannualy the shows, it work and find subtitle but after i update again they dissaper from show.json

**Comment by AlixBa** [comment]
Hi,
Sorry for the delay. Looking into it :)

**Comment by mabogdan1981** [comment]
No problem. For unknown reason, now it's working again so i don't know where was the problem.

**Comment by AlixBa** [comment]
I let this open. Ping if it happens again

**Comment by mabogdan1981** [comment]
Sure. Anyway, thank you for response.
