### ISSUE TITLE
Register package on packagist.org

### ISSUE THREAD

**Issue by martinlindhe** [AlixBa/addic7ed-subtitles#5]
Hello!

Would you please register this package on packagist.org ? 

Then one will be able to install this command line tool using "composer global require alixba/addic7ed-subtitles" (or similar), assuming composer:s bin is in your path you would then be good to go!

**Comment by AlixBa** [comment]
Hi,
will do :)

**Comment by AlixBa** [comment]
https://packagist.org/packages/alixba/addic7ed-subtitles

here you go.
